name: Test run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * 1-5"   # Weekdays at 15:00 UTC (â‰ˆ 7am Pacific during standard time)

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Download the repo files
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run your script
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          CITY: "Irvine,US"
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python main.py

  
 
